### PR TITLE
Password recovery (Issue #57)

### PR DESCRIPTION
**Pull request by Tomok**
Simple password recovery functionality using e-mail.
Might require some logging - just let me know.

Also please review the JavaScript - I'm not very familiar with that language.

### CODE REVIEW

**Comment by amcgregor** [comment]
Awesome; I'll have a gander at this first thing after work.  Were you able to test the message content locally before pushing?

**Comment by Tomok** [comment]
Yes, I checked both maildir and smtp, though I had to use the
parameter-part of the url only and paste it to my localhost domain.
Though I'm pretty sure that will not cause any problems.

Am 2014-03-18 19:02, schrieb Alice Zoë Bevan–McGregor:

**Comment by amcgregor** [comment]
Just a heads up that https://github.com/bravecollective/core/blob/develop/brave/core/util/signal.py#L42-L43 configures and starts the mailer interface automatically once on application startup.  (So no need to import the Mailer class itself.)  Marrow Mailer is also [intelligent enough to apply configuration-derived message defaults if you use the resulting mailer interface instance to construct new messages](https://github.com/marrow/marrow.mailer/blob/develop/marrow/mailer/__init__.py#L150), so it unfortunately eliminates the need for all of your configuration mangling code.  For details, see the section right above this one:

https://github.com/marrow/marrow.mailer/#422-read-only-attributes

I'll continue to review as I get a chance through the day.  :)

**Comment by Tomok** [comment]
Thanks for the pointers, implemented those changes.

**Comment by Tomok** [comment]
still any points open, that I should resolve for this pull request ?

**Comment by Acidity** [comment]
Make sure that user provided usernames and email addresses are lowercase pursuant to issue #40

**Comment by Tomok** [comment]
merged current brave/develop & lowercased e-mail (recovery does not do any lookups using the username)
Also added a simple regex to e-mail field to ensure that e-mails are lowercase

**Pull request merged**
