### PR TITLE
Cache user permissions on load for the group management page.

### PR DESCRIPTION
**Pull request by Acidity**
Signed-off-by: Tyler O'Meara Tyler@TylerOMeara.com

### CODE REVIEW

**Comment by jboning** [comment]
Hm, I don't particularly like this. Ideally the user model should encapsulate whatever caching it's doing.

**Comment by Acidity** [comment]
Oh I agree, but this change has already been pushed into feature/permissions for a couple of other places as well and I noticed the significant decrease in performance when I updated so I thought I'd commit this until I had a better solution.

**Comment by jboning** [comment]
file an issue so we don't forget about it and I'll merge =)

**Comment by jboning** [comment]
Looking at this again, I'm not sure what I was thinking when I made that comment (tiredness?). I thought the controller was reaching into the user model, accessing some cache there, and using that. Just storing the set of permissions locally for use across several calls in a loop is totally fine.

(I think part of my confusion is the use of the term "caching" here. I can't come up with a good explanation why it would be an inappropriate term here. But it managed to throw me off.)

If this achieves good enough performance, I think doing it this way is better than the way in #320, since this avoids any nonobvious cache staleness. That kind of caching could still be useful if we find ourselves needing to make a lot of checks in a way where we can't just grab the set of permissions once and use it across all of the checks. But I'm inclined to avoid doing that until we have a need.

I'm really sorry for the fakeout here :(

**Pull request merged**
