### PR TITLE
Fix the proxy API for char calls.

### PR DESCRIPTION
**Pull request by Acidity**
Signed-off-by: Tyler O'Meara Tyler@TylerOMeara.com

### CODE REVIEW

**Comment by jboning** [comment]
Can we make this default to the grant's primary character if no particular character is passed in?

**Comment by Acidity** [comment]
All of the character EVE calls require the character_id, but I suppose we could add that as well.

**Comment by jboning** [comment]
Oh, I didn't realize. That's probably good enough then.

**Comment by jboning** [comment]
Hm--but we probably shouldn't 500 if they don't pass it in. Probably success=False and a reason/message. (Or choose an arbitrary key, proxy the request through to the eve API on it, and return the resulting error, heh.)

**Pull request merged**
