### PR TITLE
Fix a bug that broke the authorize buttons in the available tab,...

### PR DESCRIPTION
**Pull request by Acidity**
... and make the authorize button in the management tab work.

Signed-off-by: Tyler O'Meara Tyler@TylerOMeara.com

### CODE REVIEW

**Comment by jboning** [comment]
Hmmm, why is this (a) necessary and (b) okay? I'm really uncomfortable removing the escaping, and curious why it's not working and why this fixes it. I'd really like to find a better way to fix whatever the problem is.

**Comment by Acidity** [comment]
This bug is actually live on SOUND's auth if you want to check it there, but with the escaping the buttons direct to (in SOUND's case) https://auth.of-sound-mind.com/application/browse/http%3A%2F%2Fknees.of-sound-mind.com%2F

**Comment by jboning** [comment]
Hahah, I see. Random ideas:
- We should at the very least use the "h" filter.
- Ensuring http/https would be good, to avoid "javascript:"
- Maybe the safest thing would be another route that 302s the user to the right place

**Comment by Acidity** [comment]
@jboning I'm actually going to leave this one to you, as you seem more invested in it.

**Comment by jboning** [comment]
Okay, will try to hit this tonight or otherwise soon.

**Comment by Acidity** [comment]
http://docs.makotemplates.org/en/latest/filtering.html < Lquid wanted me to send this on to you

**Pull request closed without merging**
