### PR TITLE
Change the Development field into an actual checkbox

### PR DESCRIPTION
**Pull request by paxswill**
Figured out how to get marrow's checkboxes working.

### CODE REVIEW

**Comment by jboning** [comment]
rockin', thanks!

**Comment by Acidity** [comment]
Does this save the value of the development field? There was a bug before this change where the dev field had to be filled in every time the app settings were changed.

**Comment by jboning** [comment]
Yeah (or at least it worked when I tested it)

**Comment by paxswill** [comment]
Mhm, fixed that bug.

**Pull request merged**
